//! A byte-for-byte port of the tracer's `LogCollapsingLowestDenseDDSketch`
//! (relative accuracy 0.01, bin limit 2048) and its protobuf serialization.
//!
//! DSM's `EdgeLatency` / `PathwayLatency` / `PayloadSize` fields are the raw
//! `DDSketch` protobuf bytes produced by `@datadog/sketches-js`. To stay
//! compatible we must reproduce both the binning *and* the dense-store layout
//! exactly (including the bin-centering that pads each chunk with zeros).
//!
//! Verified against fixtures generated by the real tracer in
//! `fixtures/sketch_golden.json` (see `tools/dsm/gen_sketch_golden.js`).
//!
//! Note: this intentionally does not use `libdd-ddsketch::DDSketch` for the
//! sketch itself. The crate does provide a Datadog `DDSketch` implementation and
//! generated protobuf structs, but its public Rust API does not expose a
//! `LogCollapsingLowestDenseDDSketch` type or constructors for the tracer/DSM
//! mapping and store configuration used by `@datadog/sketches-js`.
//!
//! In the pinned `libdd-ddsketch` version, `DDSketch::default()` uses the
//! backend-oriented mapping (relative accuracy 0.007751937984496124, non-zero
//! index offset, `ln`/`floor` indexing) and its dense store does not reproduce
//! the JS tracer's chunk-centering layout. DSM pipeline stats require the JS
//! tracer wire format: relative accuracy 0.01, zero index offset, `log2`/`ceil`
//! indexing, collapse-lowest dense stores, and byte-for-byte protobuf output for
//! `EdgeLatency`, `PathwayLatency`, and `PayloadSize`. Using
//! `libdd-ddsketch::DDSketch` directly changes those serialized bytes, so this
//! local implementation is kept and guarded by tracer-generated golden fixtures.

/// Default relative accuracy used by DSM sketches.
const RELATIVE_ACCURACY: f64 = 0.01;
const BIN_LIMIT: i64 = 2048;
const CHUNK_SIZE: i64 = 128;

/// Logarithmic key mapping, mirroring `sketches-js` `LogarithmicMapping`.
#[derive(Debug, Clone, Copy)]
struct LogarithmicMapping {
    gamma: f64,
    multiplier: f64,
    min_possible: f64,
}

impl LogarithmicMapping {
    fn new(relative_accuracy: f64) -> Self {
        let i = 2.0 * relative_accuracy / (1.0 - relative_accuracy);
        let gamma = 1.0 + i;
        // KeyMapping multiplier is 1/ln1p(i); LogarithmicMapping then * ln(2).
        let multiplier = std::f64::consts::LN_2 / i.ln_1p();
        // KeyMapping.minPossible = MIN_NORMAL * gamma (MIN_NORMAL = f64::MIN_POSITIVE).
        let min_possible = f64::MIN_POSITIVE * gamma;
        Self {
            gamma,
            multiplier,
            min_possible,
        }
    }

    /// `key(v) = ceil(log2(v) * multiplier)` (offset is always 0 for DSM).
    fn key(&self, v: f64) -> i32 {
        // Match the JS `Math.log2(v) * multiplier` op order exactly.
        #[allow(clippy::cast_possible_truncation)]
        let k = (v.log2() * self.multiplier).ceil() as i32;
        k
    }
}

/// Collapse-lowest dense store, mirroring `sketches-js` `CollapsingLowestDenseStore`.
#[derive(Debug, Clone)]
struct CollapsingLowestDenseStore {
    bins: Vec<f64>,
    count: f64,
    min_key: i32,
    max_key: i32,
    offset: i32,
    is_collapsed: bool,
}

impl CollapsingLowestDenseStore {
    fn new() -> Self {
        Self {
            bins: Vec::new(),
            count: 0.0,
            // Emulate JS +Inf / -Inf sentinels for an empty store.
            min_key: i32::MAX,
            max_key: i32::MIN,
            offset: 0,
            is_collapsed: false,
        }
    }

    fn length(&self) -> i32 {
        i32::try_from(self.bins.len()).unwrap_or(i32::MAX)
    }

    #[allow(clippy::unused_self)]
    fn get_new_length(&self, new_min: i32, new_max: i32) -> usize {
        let desired = i64::from(new_max) - i64::from(new_min) + 1;
        // ceil(desired / CHUNK_SIZE) without float casts.
        let chunks = (desired + CHUNK_SIZE - 1) / CHUNK_SIZE;
        let len = (CHUNK_SIZE * chunks).min(BIN_LIMIT);
        usize::try_from(len).unwrap_or(0)
    }

    fn add(&mut self, key: i32, weight: f64) {
        let idx = self.get_index(key);
        self.bins[idx] += weight;
        self.count += weight;
    }

    fn get_index(&mut self, key: i32) -> usize {
        if key < self.min_key {
            if self.is_collapsed {
                return 0;
            }
            self.extend_range(key, key);
            if self.is_collapsed {
                return 0;
            }
        } else if key > self.max_key {
            self.extend_range(key, key);
        }
        #[allow(clippy::cast_sign_loss)]
        let idx = (key - self.offset) as usize;
        idx
    }

    fn extend_range(&mut self, key: i32, key2: i32) {
        let new_min = key.min(key2).min(self.min_key);
        let new_max = key.max(key2).max(self.max_key);

        if self.bins.is_empty() {
            self.bins = vec![0.0; self.get_new_length(new_min, new_max)];
            self.offset = new_min;
            self.adjust(new_min, new_max);
        } else if new_min >= self.min_key && new_max < self.offset + self.length() {
            self.min_key = new_min;
            self.max_key = new_max;
        } else {
            let new_length = self.get_new_length(new_min, new_max);
            if new_length > self.bins.len() {
                self.bins.resize(new_length, 0.0);
            }
            self.adjust(new_min, new_max);
        }
    }

    /// `CollapsingLowestDenseStore._adjust`.
    fn adjust(&mut self, new_min: i32, new_max: i32) {
        if new_max - new_min + 1 > self.length() {
            // Collapse the lowest bins to fit within bin_limit.
            let collapse_min = new_max - self.length() + 1;
            if collapse_min >= self.max_key {
                self.offset = collapse_min;
                self.min_key = collapse_min;
                self.bins.iter_mut().for_each(|b| *b = 0.0);
                self.bins[0] = self.count;
            } else {
                let shift = self.offset - collapse_min;
                if shift < 0 {
                    #[allow(clippy::cast_sign_loss)]
                    let n = (self.min_key - self.offset) as usize;
                    #[allow(clippy::cast_sign_loss)]
                    let r = (collapse_min - self.offset) as usize;
                    let s: f64 = self.bins[n..=r].iter().sum();
                    self.bins[n..r].iter_mut().for_each(|b| *b = 0.0);
                    self.bins[r] += s;
                    self.min_key = collapse_min;
                    self.shift_bins(shift);
                } else {
                    self.min_key = collapse_min;
                    self.shift_bins(shift);
                }
            }
            self.max_key = new_max;
            self.is_collapsed = true;
        } else {
            self.center_bins(new_min, new_max);
            self.min_key = new_min;
            self.max_key = new_max;
        }
    }

    fn center_bins(&mut self, new_min: i32, new_max: i32) {
        let middle_key = new_min + (new_max - new_min + 1) / 2;
        let shift = (self.offset + self.length() / 2) - middle_key;
        self.shift_bins(shift);
    }

    fn shift_bins(&mut self, shift: i32) {
        if shift > 0 {
            #[allow(clippy::cast_sign_loss)]
            let s = shift as usize;
            let keep = self.bins.len() - s;
            let mut new_bins = vec![0.0; s];
            new_bins.extend_from_slice(&self.bins[..keep]);
            self.bins = new_bins;
        } else if shift < 0 {
            #[allow(clippy::cast_sign_loss)]
            let a = (-shift) as usize;
            let mut new_bins = self.bins[a..].to_vec();
            new_bins.resize(self.bins.len(), 0.0);
            self.bins = new_bins;
        }
        self.offset -= shift;
    }
}

/// A `DDSketch` matching the tracer's `LogCollapsingLowestDenseDDSketch`.
#[derive(Debug, Clone)]
pub struct DdSketch {
    mapping: LogarithmicMapping,
    store: CollapsingLowestDenseStore,
    negative_store: CollapsingLowestDenseStore,
    zero_count: f64,
}

impl Default for DdSketch {
    fn default() -> Self {
        Self::new()
    }
}

impl DdSketch {
    #[must_use]
    pub fn new() -> Self {
        Self {
            mapping: LogarithmicMapping::new(RELATIVE_ACCURACY),
            store: CollapsingLowestDenseStore::new(),
            negative_store: CollapsingLowestDenseStore::new(),
            zero_count: 0.0,
        }
    }

    /// Accept a single value (weight 1), mirroring `DDSketch.accept`.
    pub fn accept(&mut self, value: f64) {
        if value > self.mapping.min_possible {
            let key = self.mapping.key(value);
            self.store.add(key, 1.0);
        } else if value < -self.mapping.min_possible {
            let key = self.mapping.key(-value);
            self.negative_store.add(key, 1.0);
        } else {
            self.zero_count += 1.0;
        }
    }

    /// Serialize to the `DDSketch` protobuf wire format.
    #[must_use]
    pub fn to_proto_bytes(&self) -> Vec<u8> {
        let mut out = Vec::new();

        // Field 1: mapping (IndexMapping), length-delimited.
        let mut mapping = Vec::new();
        write_tag(&mut mapping, 1, WIRE_FIXED64);
        mapping.extend_from_slice(&self.mapping.gamma.to_le_bytes());
        write_tag(&mut mapping, 2, WIRE_FIXED64);
        mapping.extend_from_slice(&0.0f64.to_le_bytes()); // indexOffset
        write_tag(&mut mapping, 3, WIRE_VARINT);
        mapping.push(0); // interpolation = NONE
        write_tag(&mut out, 1, WIRE_LEN);
        write_uvarint(&mut out, mapping.len() as u64);
        out.extend_from_slice(&mapping);

        // Field 2: positiveValues (Store).
        write_tag(&mut out, 2, WIRE_LEN);
        let pos = encode_store(&self.store);
        write_uvarint(&mut out, pos.len() as u64);
        out.extend_from_slice(&pos);

        // Field 3: negativeValues (Store).
        write_tag(&mut out, 3, WIRE_LEN);
        let neg = encode_store(&self.negative_store);
        write_uvarint(&mut out, neg.len() as u64);
        out.extend_from_slice(&neg);

        // Field 4: zeroCount (double) — always emitted (matches sketches-js).
        write_tag(&mut out, 4, WIRE_FIXED64);
        out.extend_from_slice(&self.zero_count.to_le_bytes());

        out
    }
}

const WIRE_VARINT: u8 = 0;
const WIRE_FIXED64: u8 = 1;
const WIRE_LEN: u8 = 2;

fn write_tag(buf: &mut Vec<u8>, field: u32, wire: u8) {
    write_uvarint(buf, u64::from((field << 3) | u32::from(wire)));
}

fn write_uvarint(buf: &mut Vec<u8>, mut value: u64) {
    loop {
        let mut byte = (value & 0x7f) as u8;
        value >>= 7;
        if value != 0 {
            byte |= 0x80;
        }
        buf.push(byte);
        if value == 0 {
            break;
        }
    }
}

fn write_zigzag32(buf: &mut Vec<u8>, value: i32) {
    #[allow(clippy::cast_sign_loss)]
    let zz = ((value << 1) ^ (value >> 31)) as u32;
    write_uvarint(buf, u64::from(zz));
}

/// Encode a dense store: field 2 = packed `contiguousBinCounts`,
/// field 3 = `contiguousBinIndexOffset` (sint32). Field 2 is omitted when empty,
/// matching `sketches-js`.
fn encode_store(store: &CollapsingLowestDenseStore) -> Vec<u8> {
    let mut buf = Vec::new();
    if !store.bins.is_empty() {
        write_tag(&mut buf, 2, WIRE_LEN);
        write_uvarint(&mut buf, (store.bins.len() * 8) as u64);
        for &count in &store.bins {
            buf.extend_from_slice(&count.to_le_bytes());
        }
    }
    write_tag(&mut buf, 3, WIRE_VARINT);
    write_zigzag32(&mut buf, store.offset);
    buf
}

#[cfg(test)]
#[allow(clippy::unwrap_used)]
mod tests {
    use super::*;
    use serde_json::Value;

    const GOLDEN: &str = include_str!("fixtures/sketch_golden.json");

    #[test]
    fn gamma_matches_tracer() {
        let m = LogarithmicMapping::new(RELATIVE_ACCURACY);
        assert_eq!(hex::encode(m.gamma.to_le_bytes()), "fd4a815abf52f03f");
    }

    #[test]
    fn matches_all_golden_vectors() {
        let golden: Value = serde_json::from_str(GOLDEN).expect("parse fixture");
        let cases = golden["cases"].as_array().expect("cases array");

        for case in cases {
            let name = case["name"].as_str().unwrap();
            let mut sketch = DdSketch::new();
            for v in case["values"].as_array().unwrap() {
                sketch.accept(v.as_f64().unwrap());
            }
            let got = hex::encode(sketch.to_proto_bytes());
            let want = case["valueHex"].as_str().unwrap();
            assert_eq!(got, want, "sketch mismatch for case `{name}`");
        }
    }
}
