variables:
  DOCKER_TARGET_IMAGE: registry.ddbuild.io/ci/datadog-lambda-extension
  DOCKER_TARGET_VERSION: latest
  # Default version for development builds
  # This will be overwritten by the tag version if it is a release.
  VERSION: dev
  # Manual trigger variables
  AGENT_BRANCH:
    description: "Branch of the datadog-agent repository to use."
    value: main
  AGENT_VERSION:
    description: "Latest release version of the datadog-agent to tag the build with."
    value: "7.55.1"
  LAYER_SUFFIX:
    description: "Suffix to be appended to the layer name (default empty)."
    value: ""

stages:
  - generate
  - build

ci image:
  stage: build
  image: registry.ddbuild.io/images/docker:20.10
  tags: ["arch:arm64"]
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" && $CI_PIPELINE_SOURCE == "push"'
      changes:
        - .gitlab/Dockerfile
      when: on_success
  variables:
    DOCKER_TARGET: ${DOCKER_TARGET_IMAGE}:${DOCKER_TARGET_VERSION}
  script:
    - docker buildx build --platform linux/amd64,linux/arm64 --no-cache --pull --push --tag ${DOCKER_TARGET} -f .gitlab/Dockerfile .

.go-cache: &go-cache
  key: datadog-lambda-extension-go-cache
  policy: pull

generator:
  stage: generate
  image: registry.ddbuild.io/images/mirror/golang:alpine
  tags: ["arch:amd64"]
  cache: *go-cache
  artifacts:
    paths:
      - .gitlab/pipeline-bottlecap.yaml
      - .gitlab/pipeline-go-agent.yaml
      - .gitlab/pipeline-lambda-extension.yaml
    reports:
      dotenv: .env
  script:
    - if [[ "$CI_COMMIT_TAG" =~ ^v[0-9]+$ ]]; then echo "VERSION=${CI_COMMIT_TAG//[!0-9]/}" >> .env; fi
    - apk add --no-cache gomplate
    - gomplate --config .gitlab/config.yaml

bottlecap-only:
  stage: build
  trigger:
    include:
      - artifact: .gitlab/pipeline-bottlecap.yaml
        job: generator
    strategy: depend
  rules:
    - when: on_success

go-agent-only:
  stage: build
  trigger:
    include:
      - artifact: .gitlab/pipeline-go-agent.yaml
        job: generator
    strategy: depend
  rules:
    - if: $CI_PIPELINE_SOURCE == "web"
      when: manual
  variables:
    AGENT_BRANCH: $AGENT_BRANCH
    LAYER_SUFFIX: $LAYER_SUFFIX

lambda-extension:
  stage: build
  trigger:
    include:
      - artifact: .gitlab/pipeline-lambda-extension.yaml
        job: generator
    strategy: depend
  needs:
    - job: generator
      artifacts: true
  rules:
    - if: $CI_PIPELINE_SOURCE == "web"
  variables:
    VERSION: $VERSION
    AGENT_BRANCH: $AGENT_BRANCH
    LAYER_SUFFIX: $LAYER_SUFFIX
    AGENT_VERSION: $AGENT_VERSION
