image: registry.ddbuild.io/images/mirror/python:3.9

stages:
  - first
  - second

first-job:
  stage: first
  tags: ["runner:main"]
  script:
    - pip3 install awscli==1.27.85
    - externalID=$(aws ssm get-parameter 
      --region us-east-1 
      --name ci.datadog-lambda-extension.externalid 
      --with-decryption 
      --query "Parameter.Value" 
      --out text)
    - aws sts assume-role 
      --role-arn "arn:aws:iam::425362996713:role/sandbox-layer-deployer" 
      --role-session-name "publishSession"
      --external-id $externalID
    - aws lambda list-layer-versions --layer-name Datadog-Extension --region us-east-1

second-job:
  stage: second
  tags: ["runner:main"]
  script:
    - echo "Test second step"