variables:
  GIT_DEPTH: 1

image: 486234852809.dkr.ecr.us-east-1.amazonaws.com/docker:20.10-py3

stages:
  - build_tools_if_needed
  - release_layer

build:
  stage: build_tools_if_needed
  variables:
    CI_ENABLE_CONTAINER_IMAGE_BUILDS: "true"
    TARGET: 486234852809.dkr.ecr.us-east-1.amazonaws.com/ci/datadog-lambda-extension
  rules:
    - changes:
      - build-tools/**/*
  tags: ["runner:docker"]
  script:
    - cd build-tools && docker buildx build --tag ${TARGET} --push .

release:
  stage: release_layer
  tags: ["runner:docker"]
  variables:
    TARGET: 486234852809.dkr.ecr.us-east-1.amazonaws.com/ci/datadog-lambda-extension
  script:
    - git clone --depth=1 https://github.com/DataDog/datadog-agent.git
    - dockerId=$(docker create --platform linux/amd64 ${TARGET})
    - docker cp $dockerId:/build_tools .
    - externalID=$(aws ssm get-parameter 
      --region us-east-1 
      --name ci.datadog-lambda-extension.externalid 
      --with-decryption 
      --query "Parameter.Value" 
      --out text)
    - cred=$(aws sts assume-role 
      --role-arn "arn:aws:iam::425362996713:role/sandbox-layer-deployer" 
      --role-session-name "publishSession"
      --query '[Credentials.AccessKeyId,Credentials.SecretAccessKey,Credentials.SessionToken]'
      --external-id $externalID
      --output text)
    - ACCESS_KEY_ID=$(echo "$cred" | awk '{ print $1 }')
    - export AWS_ACCESS_KEY_ID=$ACCESS_KEY_ID
    - SECRET_ACCESS_KEY=$(echo "$cred" | awk '{ print $2 }')
    - export AWS_SECRET_ACCESS_KEY=$SECRET_ACCESS_KEY
    - SESSION_TOKEN=$(echo "$cred" | awk '{ print $3 }')
    - export AWS_SESSION_TOKEN=$SESSION_TOKEN
    - ./build_tools
      build
      --version 1
      --agent-version 1
      --architecture amd64
      --context-path .
      --destination-path /tmp/serverless
      --docker-path "scripts_v2/Dockerfile.build"
      --artifact-name "datadog_extension.zip"
    - ./build_tools
      sign 
      --layer-path /tmp/serverless/datadog_extension.zip 
      --destination-path /tmp/serverless/datadog_extension_signed.zip 
    - ./build_tools
      deploy
      --layer-path /tmp/serverless/datadog_extension_signed.zip
      --architecture amd64
      --layer-name "Datadog-Extension"
      --layer-suffix ""
      --region sa-east-1