variables:
  GIT_DEPTH: 0

image: 486234852809.dkr.ecr.us-east-1.amazonaws.com/docker:20.10-py3

stages:
  - build_tools_if_needed

build:
  stage: build_tools_if_needed
  variables:
    CI_ENABLE_CONTAINER_IMAGE_BUILDS: "true"
  # rules:
  # - changes:
  #   - build-tools/**/*
  # cache:
  #   - key:
  #       files:
  #         - build-tools/Cargo.lock
  #     paths:
  #       - build-tools/target
  #       - ~/.cargo
  tags: ["runner:main"]
  script:
    - cd build-tools && docker buildx build --tag datadog/build-tools .