stages:
  - first
  - second

first-job:
  stage: first
  tags: ["runner:main"]
  script:
    - aws iam get-role --role-name ci-datadog-lambda-extension

second-job:
  stage: second
  tags: ["runner:main"]
  script:
    - echo "Test second step"