image: registry.ddbuild.io/images/mirror/python:3.9

stages:
  - first
  - second

first-job:
  stage: first
  tags: ["runner:main"]
  variables:
    PIPELINE_EXECUTION_ROLE: {{pipeline_execution_role}}
  script:
    - pip3 install awscli==1.27.85
    - ./ci-script/assume-role.sh ${PIPELINE_EXECUTION_ROLE} ci-datadog-lambda-extension

second-job:
  stage: second
  tags: ["runner:main"]
  script:
    - echo "Test second step"