variables:
  GIT_DEPTH: 0

image: 486234852809.dkr.ecr.us-east-1.amazonaws.com/docker:20.10-py3

stages:
  - build_tools_if_needed

build:
  stage: build_tools_if_needed
  variables:
    CI_ENABLE_CONTAINER_IMAGE_BUILDS: "true"
    TARGET: 486234852809.dkr.ecr.us-east-1.amazonaws.com/ci/datadog-lambda-extension/serverless-build-tools
  # rules:
  # - changes:
  #   - build-tools/**/*
  # cache:
  #   - key:
  #       files:
  #         - build-tools/Cargo.lock
  #     paths:
  #       - build-tools/target
  #       - ~/.cargo
  tags: ["runner:main"]
  script:
    - rm /root/.docker/config.json
    - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 486234852809.dkr.ecr.us-east-1.amazonaws.com
    - cd build-tools && docker buildx build --tag ${TARGET} --push .
  retry: 2



  