variables:
  DOCKER_TARGET_IMAGE: registry.ddbuild.io/ci/datadog-lambda-extension
  DOCKER_TARGET_VERSION: latest

stages:
  - build
  - test
  - deploy

ci image:
  stage: build
  image: registry.ddbuild.io/images/docker:20.10-py3
  tags: ["arch:arm64"]
  # rules:
  #   - if: '$CI_COMMIT_BRANCH == "main" && $CI_PIPELINE_SOURCE == "push"'
  #     when: on_success
  variables:
    DOCKER_TARGET: ${DOCKER_TARGET_IMAGE}:${DOCKER_TARGET_VERSION}
  script:
    - docker buildx build --platform linux/amd64,linux/arm64 --no-cache --pull --push --tag ${DOCKER_TARGET} .gitlab/Dockerfile

build layer:
  stage: build
  tags: ["arch:arm64"]
  image: registry.ddbuild.io/images/docker:24.0.5
  artifacts:
    expire_in: 1 hr
    paths:
      - .layers/datadog_bottlecap-arm64.zip
  script:
    - ARCHITECTURE=arm64 ./scripts/build_bottlecap_layer.sh

fmt:
  stage: test
  tags: ["arch:arm64"]
  image: ${DOCKER_TARGET_IMAGE}:${DOCKER_TARGET_VERSION}
  # needs: []
  script:
    - cargo fmt

check:
  stage: test
  tags: ["arch:arm64"]
  image: ${DOCKER_TARGET_IMAGE}:${DOCKER_TARGET_VERSION}
  # needs: []
  script:
    - cargo check

clippy:
  stage: test
  tags: ["arch:arm64"]
  image: ${DOCKER_TARGET_IMAGE}:${DOCKER_TARGET_VERSION}
  # needs: []
  script:
    - cargo clippy --all-features
