variables:
  GIT_DEPTH: 0

image: registry.ddbuild.io/images/mirror/ubuntu:20.04

stages:
  - build

build:
  stage: build
  cache:
    - key:
        files:
          - build-tools/Cargo.lock
      paths:
        - build-tools/target
        - ~/.cargo

  #when: manual
  tags: ["runner:main"]
  script:
    - apt-get install curl -y
    - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
    - source $HOME/.cargo/env
    - cd build-tools
    - cargo test
    - cargo build --release