image: registry.ddbuild.io/images/mirror/python:3.9

stages:
  - first
  - second

first-job:
  stage: first
  tags: ["runner:main"]
  script:
    - pip3 install awscli==1.27.85
    - aws lambda list-layer-versions --layer-name Datadog-Extension --region us-east-1

second-job:
  stage: second
  tags: ["runner:main"]
  script:
    - echo "Test second step"