FROM scratch
COPY .layers/datadog_extension-$SUFFIX/extensions/datadog-agent opt/extensions/datadog-agent
COPY .layers/datadog_extension-$SUFFIX/datadog-agent-go opt/datadog-agent-go
COPY --chmod=0755 scripts/datadog_wrapper opt/datadog_wrapper

