[package]
name = "build_tools"
version = "0.1.0"
edition = "2021"

[dependencies]
aws-config = "0.51.0"
aws-sdk-lambda = "0.21.0"
aws-sdk-s3 = "0.21.0"
aws-sdk-signer = "0.21.0"
aws-sdk-sts = "0.21.0"
rand = "0.8.5"
structopt = "0.3.26"
tokio = { version = "1", features = ["full"] }
