environments:
  - name: sandbox
    external_id: sandbox-publish-externalid
    role_to_assume: sandbox-layer-deployer
    account: 425362996713
    add_permissions: 0
    automatically_bump_version: 1
  - name: prod
    external_id: prod-publish-externalid
    role_to_assume: dd-serverless-layer-deployer-role
    account: 464622532012
    add_permissions: 1
    automatically_bump_version: 0
