service: integration-tests-lambda-extension

resources:
    Description: "[Serverless] Integration tests application for lambda extension"

provider:
  name: aws
  region: sa-east-1
  tracing:
    lambda: true
    apiGateway: true
  environment:
    DD_INTEGRATION_TEST: true
    DD_API_KEY: NO_NEED_TO_BE_VALID
    DD_LOG_LEVEL: DEBUG
  lambdaHashingVersion: 20201221
  timeout: 15
  deploymentBucket:
    name: integration-tests-deployment-bucket
  iam:
    # IAM permissions require that all functions are deployed with this role
    role: "arn:aws:iam::601427279990:role/serverless-integration-test-lambda-role"

layers:
  manInTheMiddleExtension:
    package:
      artifact: ./man-in-the-middle-extension/ext.zip

functions:
  #actual testing functions
  enhancedMetricTest:
    name: integration-tests-lambda-extension-${sls:stage}-enhancedMetricTest
    runtime: nodejs12.x
    handler: src/metric.enhancedMetricTest
    layers:
      - arn:aws:lambda:${self:provider.region}:601427279990:layer:Datadog-Node12-x:${env:LAYER_VERSION}
      - arn:aws:lambda:${self:provider.region}:601427279990:layer:Datadog-Extension:${env:EXTENSION_VERSION}
      - {Ref: ManInTheMiddleExtensionLambdaLayer}
    environment:
      DD_DD_URL: http://127.0.0.1:3333
      DD_ENHANCED_METRICS: true

