service: integration-tests-lambda-extension

# -------------------------------------------------------------------------------------------
# this is required to make sure that API Gateway is NOT trying to encode the payload in UTF8
# which makes the unmarshalling of protobuf impossible
# API Gateway will watch for this content-type and base64 encode the binary payload
#plugins:
#  - serverless-apigw-binary 
#custom:
#  apigwBinary:
#    types:           
#      - 'application/x-protobuf'
# -------------------------------------------------------------------------------------------

resources:
    Description: "[Serverless] Integration tests application for lambda extension"

provider:
  name: aws
  region: sa-east-1
  tracing:
    lambda: true
    apiGateway: true
  environment:
    DD_INTEGRATION_TEST: true
    DD_API_KEY: NO_NEED_TO_BE_VALID
  lambdaHashingVersion: 20201221
  timeout: 15
  deploymentBucket:
    name: integration-tests-deployment-bucket
  iam:
    # IAM permissions require that all functions are deployed with this role
    role: "arn:aws:iam::601427279990:role/serverless-integration-test-lambda-role"

functions:
  #actual testing functions
  metricTest:
    name: integration-tests-lambda-extension-${sls:stage}-metricTest
    runtime: nodejs12.x
    handler: src/metric.metricTest
    events:
      - http:
          path: metricTest
          method: get
    layers:
      - arn:aws:lambda:${self:provider.region}:601427279990:layer:Datadog-Node12-x:${env:LAYER_VERSION}
      - arn:aws:lambda:${self:provider.region}:601427279990:layer:Datadog-Extension:${env:EXTENSION_VERSION}
    environment:
      DD_ENHANCED_METRICS: true

 