version: '3.8'
services:
  rust:
    build:
      context: .
      dockerfile: .devcontainer/rust/Dockerfile

  rie:
    build:
      context: .
      dockerfile: .devcontainer/rie/Dockerfile
    ports:
        - "9000:8080"
    volumes:
        - ${PWD}/lambda:/var/task/lambda