FROM scratch
ARG TARGETARCH
ARG SUFFIX

COPY .layers/datadog_extension-${TARGETARCH}${SUFFIX}/extensions/datadog-agent opt/extensions/datadog-agent
COPY --chmod=0755 scripts/datadog_wrapper opt/datadog_wrapper
