ARG UBUNTU_IMAGE=registry.ddbuild.io/images/mirror/ubuntu:22.04

FROM ${UBUNTU_IMAGE} AS compresser
ARG FILE_SUFFIX

RUN apt-get update && apt-get install -y zip binutils

# Copy Go Agent from last release
COPY --from=public.ecr.aws/datadog/lambda-extension:latest /opt/datadog-agent-go  /datadog-agent-go
RUN mkdir /extensions
WORKDIR /extensions

RUN --mount=type=bind,source=.binaries/bottlecap-${FILE_SUFFIX},target=/extensions/datadog-agent \
    --mount=type=bind,source=./scripts/datadog_wrapper,target=/datadog_wrapper,rw \
    chmod +x /datadog_wrapper && \
    zip -r datadog_extension.zip /extensions /datadog_wrapper /datadog-agent-go

# keep the smallest possible docker image
FROM scratch
COPY --from=compresser /extensions/datadog_extension.zip /
ENTRYPOINT ["/datadog_extension.zip"]
