FROM gcr.io/distroless/cc-debian12
COPY --from=busybox:1.35.0-uclibc /bin/sh /bin/sh
ARG TARGETARCH

COPY ./bin/datadog_extension-$TARGETARCH/extensions/datadog-agent /datadog-init
COPY ./bin/datadog_extension-$TARGETARCH/extensions/dotnet.sh /datadog-init/dotnet.sh

ENTRYPOINT ["/datadog-init"]