# DD Octo STS Trust Policy for serverless-init-ci GitLab pipeline
#
# This policy allows the serverless-init-ci GitLab pipeline to publish
# serverless-init images to GitHub Container Registry (GHCR).
#
# Reference: https://datadoghq.atlassian.net/wiki/spaces/SECENG/pages/5138645099
# Pipeline: https://gitlab.ddbuild.io/DataDog/serverless-init-ci

issuer: https://gitlab.ddbuild.io

# Subject pattern matches the serverless-init-ci repo on any branch or tag
subject_pattern: "project_path:DataDog/serverless-init-ci:ref_type:(branch|tag):ref:.*"

# Allow all branches and tags for building RC and prod images
claim_pattern:
  project_path: "DataDog/serverless-init-ci"
  ref_type: "^(branch|tag)$"
  pipeline_source: "^(web|pipeline|push)$"

# Minimal permissions: only write packages to GHCR
permissions:
  packages: write
  metadata: read