name: bottlecap

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: unit tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: bottlecap
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Run Tests
        run: cargo test --verbose
  
  format:
    name: fmt
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: bottlecap

    steps:
      - uses: actions/checkout@v3
      
      - name: Format
        run: cargo fmt --verbose

  clippy:
    name: clippy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: bottlecap

    steps:
      - uses: actions/checkout@v3
      
      - name: Format
        run: cargo clippy --verbose
