name: Poc Build

on:
  push:
    branches: [ maxday/release-extension-github-actions ]
  workflow_dispatch:
    inputs:
      release_candidate:
        type: boolean
        description: Publish a new release candidate

jobs:
  build-extension-zip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          repository: DataDog/datadog-agent
          ref: refs/tags/lambda-extension-32
          path: datadog-agent
      - run: |
         ./build-tools/bin/build_tools \
         --version 1 \
         --agent-version 1 \
         --context-path "${GITHUB_WORKSPACE}" \
         --destination-path "${GITHUB_WORKSPACE}/tmp"
      - uses: actions/upload-artifact@v3
        with:
          name: datadog-extension
          path: ./tmp/datadog_extension.zip  