name: Poc Build

on:
  push:
    branches: [ maxday/release-extension-github-actions ]
  workflow_dispatch:
    inputs:
      release_candidate:
        type: bool
        description: Publish a new release candidate

jobs:
  auth:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cd build-tools && cargo run --release