name: Poc Build

on:
  workflow_dispatch:
    inputs:
      release_candidate:
        type: bool
        description: Publish a new release candidate

jobs:
  auth:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: pwd