name: Poc Build

on:
  push:
    branches: [ maxday/release-extension-github-actions ]
  workflow_dispatch:
    inputs:
      release_candidate:
        type: bool
        description: Publish a new release candidate

jobs:
  build-extension-zip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions/checkout@v2
        with:
          repository: DataDog/datadog-agent
          ref: refs/tags/lambda-extension-32
          path: datadog-agent
      - run: pwd
      - run: ls
      - run: echo "${GITHUB_WORKSPACE}"
      - run: ls "${GITHUB_WORKSPACE}"/datadog-agent
      - run: cd build-tools && cargo run --release -- --version 1 --agent-version 1 --context-path "${GITHUB_WORKSPACE}" --destination-path "${GITHUB_WORKSPACE}/tmp"
      - run: pwd
      - uses: actions/upload-artifact@v3
        with:
          name: datadog-extension
          path: ./tmp/datadog_extension.zip  