name: Poc Build

on:
  push:
    branches: [ maxday/release-extension-github-actions ]
  workflow_dispatch:
    inputs:
      release_candidate:
        type: bool
        description: Publish a new release candidate

jobs:
  build-extension-zip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions/checkout@v2
        with:
          repository: DataDog/datadog-agent
          ref: refs/tags/lambda-extension-32
          path: /tmp/datadog-agent
      - run: ls /tmp/datadog-agent
      - run: cd build-tools && cargo run --release -- --version 1 --context-path "$(pwd)/.." --destination-path /tmp
      - uses: actions/upload-artifact@v3
        with:
          name: datadog-extension
          path: /tmp/datadog_extension.zip