name: Poc Build

on:
  #push:
  #  branches: [ maxday/release-extension-github-actions ]
  workflow_dispatch:
    inputs:
      mfaCode:
        type: string
        description: MFA Code
        required: true

jobs:
  build-extension-zip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: auth
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.GH_ACTION_PUBLISHER_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.GH_ACTION_PUBLISHER_AWS_SECRET_ACCESS_KEY }}
        run: |
          ./build-tools/bin/build_tools \
          auth \
          --mfa-arn ${{ secrets.GH_ACTION_PUBLISHER_MFA_DEVICE_ARN }} \
          --mfa-code ${{ inputs.mfaCode }}
      - name: Add mask
        run: |
          echo "::add-mask::${{ env.AWS_ACCESS_KEY_ID }}" 
          echo "::add-mask::${{ env.AWS_SECRET_ACCESS_KEY }}" 
          echo "::add-mask::${{ env.AWS_SESSION_TOKEN }}" 
      - uses: actions/checkout@v3
        with:
          repository: DataDog/datadog-agent
          ref: refs/tags/lambda-extension-32
          path: datadog-agent
      - run: |
         ./build-tools/bin/build_tools \
         build \
         --version 1 \
         --agent-version 1 \
         --context-path "${GITHUB_WORKSPACE}" \
         --destination-path "${GITHUB_WORKSPACE}/tmp"
      - uses: actions/upload-artifact@v3
        with:
          name: datadog-extension
          path: ./tmp/datadog_extension.zi
      - id: deploy
        run: |
          ./build-tools/bin/build_tools \
          deploy \
          --layer-path ./tmp/datadog_extension.zip \
          --layer-name "maxday-test-Datadog-Extension" \
          --region sa-east-1
