name: redirect

on:
  schedule:
    - cron: "0 12 * * *"

  workflow_dispatch: # should be deleted after manual test

jobs:
  redirect-issues:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Ping on slack issues related to serverless in the datadog-agent repo
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        run: ./scripts/redirect_issues.sh
